---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-pro-deployment

spec:
  replicas: 2

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: gym-pro

  template:
    metadata:
      labels:
        app: gym-pro

    spec:
      containers:
        - name: gym-pro-container
          image: gym-pro:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: gym-pro

spec:
  type: LoadBalancer

  selector:
    app: gym-pro

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80